apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventsubscriptions.luma.serverframework.com
spec:
  group: luma.serverframework.com
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
      - name: Queue
        type: string
        jsonPath: .spec.queue
      - name: ApiNamespace
        type: string
        jsonPath: .spec.apiNamespace
      - name: Service
        type: string
        jsonPath: .spec.service
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                filtersHashsum:
                  type: string
                service:
                  type: string
                apiNamespace:
                  type: string
                queue:
                  type: string
                filters:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    kind: EventSubscription
    plural: eventsubscriptions
    singular: eventsubscription
    shortNames:
    - subscriptions
