apiVersion: v1
kind: ServiceAccount
metadata:
  name: sf-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sf-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get"]
  - apiGroups: ["luma.serverframework.com"]
    resources:
      ["eventsubscriptions", "eventsubscriptions/status", "eventsubscriptions/finalizers"]
    verbs: ["get", "watch", "update", "patch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sf-operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: sf-operator-service-account
roleRef:
  kind: ClusterRole
  name: sf-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sf-operator
  template:
    metadata:
      labels:
        app: sf-operator
    spec:
      serviceAccountName: sf-operator-service-account
      containers:
        - name: sf-operator
          image: lukas8219/sf-operator:latest
          imagePullPolicy: Always